// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rest_service.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RestError struct {
	Code                 *int32   `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Reason               *string  `protobuf:"bytes,2,req,name=reason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestError) Reset()         { *m = RestError{} }
func (m *RestError) String() string { return proto.CompactTextString(m) }
func (*RestError) ProtoMessage()    {}
func (*RestError) Descriptor() ([]byte, []int) {
	return fileDescriptor_421b47d883a4fc48, []int{0}
}

func (m *RestError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestError.Unmarshal(m, b)
}
func (m *RestError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestError.Marshal(b, m, deterministic)
}
func (m *RestError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestError.Merge(m, src)
}
func (m *RestError) XXX_Size() int {
	return xxx_messageInfo_RestError.Size(m)
}
func (m *RestError) XXX_DiscardUnknown() {
	xxx_messageInfo_RestError.DiscardUnknown(m)
}

var xxx_messageInfo_RestError proto.InternalMessageInfo

func (m *RestError) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *RestError) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*RestError)(nil), "org.jetrtc.api.RestError")
}

func init() { proto.RegisterFile("rest_service.proto", fileDescriptor_421b47d883a4fc48) }

var fileDescriptor_421b47d883a4fc48 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x4a, 0x2d, 0x2e,
	0x89, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0xcb, 0x2f, 0x4a, 0xd7, 0xcb, 0x4a, 0x2d, 0x29, 0x2a, 0x49, 0xd6, 0x4b, 0x2c, 0xc8, 0x54, 0x32,
	0xe7, 0xe2, 0x0c, 0x4a, 0x2d, 0x2e, 0x71, 0x2d, 0x2a, 0xca, 0x2f, 0x12, 0x12, 0xe2, 0x62, 0x49,
	0xce, 0x4f, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd2, 0x60, 0x0d, 0x02, 0xb3, 0x85, 0xc4, 0xb8, 0xd8,
	0x8a, 0x52, 0x13, 0x8b, 0xf3, 0xf3, 0x24, 0x98, 0x14, 0x98, 0x34, 0x38, 0x83, 0xa0, 0x3c, 0x27,
	0xd6, 0x28, 0xe6, 0xc4, 0x82, 0x4c, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x74, 0x96, 0x5e,
	0x64, 0x00, 0x00, 0x00,
}
