// Code generated by protoc-gen-go. DO NOT EDIT.
// source: video_service.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AssignICEServersRequest struct {
	TimeToLive           *int64   `protobuf:"varint,1,opt,name=time_to_live,json=timeToLive" json:"time_to_live,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignICEServersRequest) Reset()         { *m = AssignICEServersRequest{} }
func (m *AssignICEServersRequest) String() string { return proto.CompactTextString(m) }
func (*AssignICEServersRequest) ProtoMessage()    {}
func (*AssignICEServersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55612d58104f18be, []int{0}
}

func (m *AssignICEServersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignICEServersRequest.Unmarshal(m, b)
}
func (m *AssignICEServersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignICEServersRequest.Marshal(b, m, deterministic)
}
func (m *AssignICEServersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignICEServersRequest.Merge(m, src)
}
func (m *AssignICEServersRequest) XXX_Size() int {
	return xxx_messageInfo_AssignICEServersRequest.Size(m)
}
func (m *AssignICEServersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignICEServersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssignICEServersRequest proto.InternalMessageInfo

func (m *AssignICEServersRequest) GetTimeToLive() int64 {
	if m != nil && m.TimeToLive != nil {
		return *m.TimeToLive
	}
	return 0
}

type AssignICEServersResponse struct {
	IceServers           []*ICEServer `protobuf:"bytes,1,rep,name=ice_servers,json=iceServers" json:"ice_servers,omitempty"`
	TimeToLive           *int64       `protobuf:"varint,2,opt,name=time_to_live,json=timeToLive" json:"time_to_live,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AssignICEServersResponse) Reset()         { *m = AssignICEServersResponse{} }
func (m *AssignICEServersResponse) String() string { return proto.CompactTextString(m) }
func (*AssignICEServersResponse) ProtoMessage()    {}
func (*AssignICEServersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55612d58104f18be, []int{1}
}

func (m *AssignICEServersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignICEServersResponse.Unmarshal(m, b)
}
func (m *AssignICEServersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignICEServersResponse.Marshal(b, m, deterministic)
}
func (m *AssignICEServersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignICEServersResponse.Merge(m, src)
}
func (m *AssignICEServersResponse) XXX_Size() int {
	return xxx_messageInfo_AssignICEServersResponse.Size(m)
}
func (m *AssignICEServersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignICEServersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AssignICEServersResponse proto.InternalMessageInfo

func (m *AssignICEServersResponse) GetIceServers() []*ICEServer {
	if m != nil {
		return m.IceServers
	}
	return nil
}

func (m *AssignICEServersResponse) GetTimeToLive() int64 {
	if m != nil && m.TimeToLive != nil {
		return *m.TimeToLive
	}
	return 0
}

type JoinRoomRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomRequest) Reset()         { *m = JoinRoomRequest{} }
func (m *JoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRequest) ProtoMessage()    {}
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55612d58104f18be, []int{2}
}

func (m *JoinRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRequest.Unmarshal(m, b)
}
func (m *JoinRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRequest.Marshal(b, m, deterministic)
}
func (m *JoinRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRequest.Merge(m, src)
}
func (m *JoinRoomRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRequest.Size(m)
}
func (m *JoinRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRequest proto.InternalMessageInfo

type JoinRoomResponse struct {
	Url                  *string      `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	IceServers           []*ICEServer `protobuf:"bytes,2,rep,name=ice_servers,json=iceServers" json:"ice_servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *JoinRoomResponse) Reset()         { *m = JoinRoomResponse{} }
func (m *JoinRoomResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResponse) ProtoMessage()    {}
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55612d58104f18be, []int{3}
}

func (m *JoinRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResponse.Unmarshal(m, b)
}
func (m *JoinRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResponse.Marshal(b, m, deterministic)
}
func (m *JoinRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResponse.Merge(m, src)
}
func (m *JoinRoomResponse) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResponse.Size(m)
}
func (m *JoinRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResponse proto.InternalMessageInfo

func (m *JoinRoomResponse) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *JoinRoomResponse) GetIceServers() []*ICEServer {
	if m != nil {
		return m.IceServers
	}
	return nil
}

type ReportRoomConnectionRequest struct {
	Timestamp            *int64    `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	Local                *Endpoint `protobuf:"bytes,2,req,name=local" json:"local,omitempty"`
	Remote               *Endpoint `protobuf:"bytes,3,req,name=remote" json:"remote,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReportRoomConnectionRequest) Reset()         { *m = ReportRoomConnectionRequest{} }
func (m *ReportRoomConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRoomConnectionRequest) ProtoMessage()    {}
func (*ReportRoomConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55612d58104f18be, []int{4}
}

func (m *ReportRoomConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRoomConnectionRequest.Unmarshal(m, b)
}
func (m *ReportRoomConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRoomConnectionRequest.Marshal(b, m, deterministic)
}
func (m *ReportRoomConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRoomConnectionRequest.Merge(m, src)
}
func (m *ReportRoomConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRoomConnectionRequest.Size(m)
}
func (m *ReportRoomConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRoomConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRoomConnectionRequest proto.InternalMessageInfo

func (m *ReportRoomConnectionRequest) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ReportRoomConnectionRequest) GetLocal() *Endpoint {
	if m != nil {
		return m.Local
	}
	return nil
}

func (m *ReportRoomConnectionRequest) GetRemote() *Endpoint {
	if m != nil {
		return m.Remote
	}
	return nil
}

type ICEServer struct {
	Urls                 []string `protobuf:"bytes,1,rep,name=urls" json:"urls,omitempty"`
	Username             *string  `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Credential           *string  `protobuf:"bytes,3,opt,name=credential" json:"credential,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ICEServer) Reset()         { *m = ICEServer{} }
func (m *ICEServer) String() string { return proto.CompactTextString(m) }
func (*ICEServer) ProtoMessage()    {}
func (*ICEServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_55612d58104f18be, []int{5}
}

func (m *ICEServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ICEServer.Unmarshal(m, b)
}
func (m *ICEServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ICEServer.Marshal(b, m, deterministic)
}
func (m *ICEServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ICEServer.Merge(m, src)
}
func (m *ICEServer) XXX_Size() int {
	return xxx_messageInfo_ICEServer.Size(m)
}
func (m *ICEServer) XXX_DiscardUnknown() {
	xxx_messageInfo_ICEServer.DiscardUnknown(m)
}

var xxx_messageInfo_ICEServer proto.InternalMessageInfo

func (m *ICEServer) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *ICEServer) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *ICEServer) GetCredential() string {
	if m != nil && m.Credential != nil {
		return *m.Credential
	}
	return ""
}

type Endpoint struct {
	Identity             *string  `protobuf:"bytes,1,req,name=identity" json:"identity,omitempty"`
	Type                 *string  `protobuf:"bytes,2,req,name=type" json:"type,omitempty"`
	Address              *string  `protobuf:"bytes,3,req,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_55612d58104f18be, []int{6}
}

func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetIdentity() string {
	if m != nil && m.Identity != nil {
		return *m.Identity
	}
	return ""
}

func (m *Endpoint) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Endpoint) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*AssignICEServersRequest)(nil), "org.jetrtc.api.AssignICEServersRequest")
	proto.RegisterType((*AssignICEServersResponse)(nil), "org.jetrtc.api.AssignICEServersResponse")
	proto.RegisterType((*JoinRoomRequest)(nil), "org.jetrtc.api.JoinRoomRequest")
	proto.RegisterType((*JoinRoomResponse)(nil), "org.jetrtc.api.JoinRoomResponse")
	proto.RegisterType((*ReportRoomConnectionRequest)(nil), "org.jetrtc.api.ReportRoomConnectionRequest")
	proto.RegisterType((*ICEServer)(nil), "org.jetrtc.api.ICEServer")
	proto.RegisterType((*Endpoint)(nil), "org.jetrtc.api.Endpoint")
}

func init() { proto.RegisterFile("video_service.proto", fileDescriptor_55612d58104f18be) }

var fileDescriptor_55612d58104f18be = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x3f, 0x6f, 0xdb, 0x30,
	0x10, 0xc5, 0x21, 0xa9, 0x6e, 0xad, 0x73, 0xd1, 0xba, 0xec, 0x50, 0xf6, 0x0f, 0x0a, 0x41, 0x93,
	0x26, 0xa1, 0xf0, 0xd8, 0x4e, 0xad, 0xe1, 0xa1, 0x45, 0x27, 0xc6, 0x53, 0x32, 0x38, 0x82, 0x74,
	0x30, 0x18, 0x48, 0x3c, 0x86, 0xa4, 0x84, 0xf8, 0xc3, 0xe4, 0xbb, 0x06, 0xa2, 0x65, 0x39, 0xb1,
	0x87, 0x20, 0xdb, 0xdd, 0x23, 0xef, 0x7e, 0xef, 0x1e, 0x7c, 0xec, 0x64, 0x85, 0xb4, 0xb1, 0x68,
	0x3a, 0x59, 0x62, 0xae, 0x0d, 0x39, 0x62, 0xef, 0xc8, 0x6c, 0xf3, 0x1b, 0x74, 0xc6, 0x95, 0x79,
	0xa1, 0x65, 0xfa, 0x0b, 0x3e, 0xfd, 0xb6, 0x56, 0x6e, 0xd5, 0xdf, 0xe5, 0xea, 0x02, 0x4d, 0x87,
	0xc6, 0x0a, 0xbc, 0x6d, 0xd1, 0x3a, 0x96, 0xc0, 0x5b, 0x27, 0x1b, 0xdc, 0x38, 0xda, 0xd4, 0xb2,
	0x43, 0x1e, 0x24, 0x41, 0x16, 0x09, 0xe8, 0xb5, 0x35, 0xfd, 0x97, 0x1d, 0xa6, 0x77, 0xc0, 0xcf,
	0x87, 0xad, 0x26, 0x65, 0x91, 0xfd, 0x84, 0x99, 0x2c, 0xd1, 0xd3, 0xd1, 0x58, 0x1e, 0x24, 0x51,
	0x36, 0x5b, 0x7c, 0xce, 0x9f, 0xe2, 0xf3, 0x71, 0x50, 0x80, 0x2c, 0x71, 0xd8, 0x71, 0x46, 0x0e,
	0xcf, 0xc8, 0x1f, 0xe0, 0xfd, 0x3f, 0x92, 0x4a, 0x10, 0x35, 0x83, 0xdd, 0xf4, 0x1a, 0xe6, 0x47,
	0x69, 0x30, 0x31, 0x87, 0xa8, 0x35, 0x35, 0x0f, 0x92, 0x30, 0x8b, 0x45, 0x5f, 0x9e, 0xda, 0x0a,
	0x5f, 0x60, 0x2b, 0xbd, 0x0f, 0xe0, 0xab, 0x40, 0x4d, 0xc6, 0xf5, 0x90, 0x25, 0x29, 0x85, 0xa5,
	0x93, 0xa4, 0x0e, 0x81, 0x7d, 0x83, 0xb8, 0xb7, 0x68, 0x5d, 0xd1, 0x68, 0xcf, 0x8c, 0xc4, 0x51,
	0x60, 0x39, 0x4c, 0x6a, 0x2a, 0x8b, 0x9a, 0x87, 0x49, 0x98, 0xcd, 0x16, 0xfc, 0x94, 0xb9, 0x52,
	0x95, 0x26, 0xa9, 0x9c, 0xd8, 0x7f, 0x63, 0x3f, 0xe0, 0xb5, 0xc1, 0x86, 0x1c, 0xf2, 0xe8, 0x99,
	0x81, 0xe1, 0x5f, 0x7a, 0x05, 0xf1, 0x68, 0x9c, 0x31, 0x78, 0xd5, 0x9a, 0x7a, 0x1f, 0x7c, 0x2c,
	0x7c, 0xcd, 0xbe, 0xc0, 0xb4, 0xb5, 0x68, 0x54, 0xd1, 0xec, 0x33, 0x8d, 0xc5, 0xd8, 0xb3, 0xef,
	0x00, 0xa5, 0xc1, 0x0a, 0x95, 0x93, 0x45, 0xcd, 0x23, 0xff, 0xfa, 0x48, 0x49, 0xd7, 0x30, 0x3d,
	0x00, 0xfb, 0x3d, 0xd2, 0xeb, 0x6e, 0x37, 0x64, 0x3b, 0xf6, 0x3d, 0xd7, 0xed, 0x34, 0xfa, 0x2b,
	0x63, 0xe1, 0x6b, 0xc6, 0xe1, 0x4d, 0x51, 0x55, 0x06, 0xad, 0xf5, 0xb7, 0xc4, 0xe2, 0xd0, 0xfe,
	0x99, 0x5c, 0x46, 0x85, 0x96, 0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x56, 0x65, 0x55, 0xe8, 0xab,
	0x02, 0x00, 0x00,
}
